name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master

jobs:
  terraform:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev]
        stack: [vpc]

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install tools
        run: |
          pipx install terraform-local

      - name: Set working directory
        id: dir
        run: |
          echo "DIR=environments/${{ matrix.environment }}/${{ matrix.stack }}" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          cd ${{ steps.dir.outputs.DIR }}
          tflocal init

      - name: Terraform Validate
        run: |
          cd ${{ steps.dir.outputs.DIR }}
          terraform validate

      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: |
          cd ${{ steps.dir.outputs.DIR }}
          tflocal plan -no-color

      - name: Terraform Apply (main)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          cd ${{ steps.dir.outputs.DIR }}
          tflocal apply -auto-approve
