name: Terraform CI/CD

on:
  push:
    branches:
      - '**'           # any branch
  pull_request:
    branches:
      - dev
      - staging
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
            - dev
        stack:
            - vpc
            - subnet

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          DEBUG: 1

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terraform Local
        run: pipx install terraform-local

      - name: Determine environment from branch
        id: env
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [[ "$BRANCH_NAME" == dev ]] || [[ "$BRANCH_NAME" == feat/dev-* ]] || [[ "$BRANCH_NAME" == fix/dev-* ]]; then
            echo "TARGET_ENV=dev" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == staging ]] || [[ "$BRANCH_NAME" == feat/staging-* ]] || [[ "$BRANCH_NAME" == fix/staging-* ]]; then
            echo "TARGET_ENV=staging" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == prod ]] || [[ "$BRANCH_NAME" == feat/prod-* ]] || [[ "$BRANCH_NAME" == fix/prod-* ]]; then
            echo "TARGET_ENV=prod" >> $GITHUB_ENV
          else
            echo "TARGET_ENV=ci" >> $GITHUB_ENV   # Any other branch = CI only
          fi
      - name: Set working directory
        id: workdir
        run: |
          echo "DIR=environments/${TARGET_ENV}/${{ matrix.stack }}" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          cd ${{ steps.workdir.outputs.DIR }}
          tflocal init

      - name: Terraform Validate
        run: |
          cd ${{ steps.workdir.outputs.DIR }}
          terraform validate

      - name: Terraform Plan
        run: |
          cd ${{ steps.workdir.outputs.DIR }}
          tflocal plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/prod')
        run: |
          cd ${{ steps.workdir.outputs.DIR }}
          tflocal apply -auto-approve
